chore: migrate to owl bot
googleapis/nodejs-tasks pull request #515
Opened 2021-04-19 23:54 UTC by SurferJeffAtGoogle

2021-04-19 23:57 UTC, grant approved these changes

2021-04-20 17:11 UTC, chingor13 requested changes

2021-04-20 17:11 UTC, chingor13 commented on owlbot.py
> +# Copyright 2018 Google LLC
Make this a git mv or fix the year?

2021-04-20 17:11 UTC, chingor13 commented on owlbot.py
> +            '"max_rpc_timeout_millis": 20000')
Is there a bug for this replacement? These values can/should be configured in the generator via the grpc_service_config.json

2021-04-20 19:08 UTC, chingor13 approved these changes

2021-04-20 19:08 UTC, chingor13 commented on owlbot.py
> +# Copyright 2018 Google LLC
Apparently git does not fully support this so we'll keep the year from the original synth.py.

2021-04-21 00:51 UTC, merged